apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend

spec:
  replicas: {{ .Values.replicas }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:

      - name: backend
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}

        ports:
        - containerPort: 3000