replicaCount: 4

image:
  repository: nginx
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: frontend.local

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"
